# Generated by Django 3.2.1 on 2023-04-25 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SJUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('area', models.CharField(max_length=20, verbose_name='地区')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别')),
                ('role', models.CharField(choices=[('雇主', '雇主'), ('设计师', '设计师')], max_length=10, verbose_name='角色')),
                ('skill', models.CharField(default='雇主无技能', max_length=255, verbose_name='技能')),
                ('introduction', models.CharField(default='雇主无简介', max_length=255, verbose_name='个人简介')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户管理',
            },
        ),
        migrations.CreateModel(
            name='SJWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, verbose_name='作品名称')),
                ('work_desc', models.CharField(max_length=255, verbose_name='作品描述')),
                ('work_create_time', models.DateTimeField(auto_now_add=True, verbose_name='作品创建时间')),
                ('work_img', models.ImageField(upload_to='work_img', verbose_name='作品图片')),
                ('work_price', models.FloatField(verbose_name='案例要价')),
                ('work_designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sjsapp.sjuser', verbose_name='设计师')),
            ],
            options={
                'verbose_name': '作品管理',
            },
        ),
        migrations.CreateModel(
            name='SJTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20, verbose_name='任务名称')),
                ('task_desc', models.CharField(max_length=255, verbose_name='任务描述')),
                ('task_status', models.CharField(choices=[('待处理', '待处理'), ('已接受', '已接受'), ('已取消', '已取消')], max_length=20, verbose_name='任务状态')),
                ('task_expect_day', models.IntegerField(verbose_name='预期天数')),
                ('task_money', models.FloatField(verbose_name='任务金额')),
                ('task_create_time', models.DateTimeField(auto_now_add=True, verbose_name='任务创建时间')),
                ('task_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_tasks', to='sjsapp.sjuser', verbose_name='任务发布者')),
                ('task_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_tasks', to='sjsapp.sjuser', verbose_name='任务接受者')),
            ],
            options={
                'verbose_name': '任务管理',
            },
        ),
        migrations.CreateModel(
            name='SJOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('进行中', '进行中'), ('已交付', '已交付'), ('已完成', '已完成'), ('已取消', '已取消')], max_length=20, verbose_name='订单状态')),
                ('order_create_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('order_amount', models.FloatField(verbose_name='订单金额')),
                ('order_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sjsapp.sjtask', verbose_name='订单所属任务')),
            ],
            options={
                'verbose_name': '订单管理',
            },
        ),
    ]
