# Generated by Django 3.2.1 on 2023-04-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sjwork',
            name='work_img',
            field=models.ImageField(upload_to='templates/work_img', verbose_name='作品图片'),
        ),
    ]
