# Generated by Django 3.2.1 on 2023-04-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjsapp', '0002_alter_sjwork_work_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sjwork',
            name='work_img',
            field=models.ImageField(upload_to='templates/assets', verbose_name='作品图片'),
        ),
    ]
