# Generated by Django 3.2.1 on 2023-04-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjsapp', '0003_alter_sjwork_work_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sjtask',
            name='task_contact',
            field=models.CharField(default=1, max_length=20, verbose_name='联系人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sjtask',
            name='task_phone',
            field=models.CharField(default=1, max_length=11, verbose_name='联系电话'),
            preserve_default=False,
        ),
    ]
