# Generated by Django 3.2.1 on 2023-04-26 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sjsapp', '0004_auto_20230426_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sjtask',
            name='task_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_tasks', to='sjsapp.sjuser', verbose_name='任务接受者'),
        ),
    ]
